randonne_index:
    path:     /
    defaults: { _controller: "ExcursionBundle:Randonne:index" }
    methods:  GET

randonne_show:
    path:     /show/{idrando}
    defaults: { _controller: "ExcursionBundle:Randonne:show" }
    methods:  GET

randonne_new:
    path:     /new
    defaults: { _controller: "ExcursionBundle:Randonne:new" }
    methods:  [GET, POST]

randonne_edit:
    path:     /edit/{idrando}
    defaults: { _controller: "ExcursionBundle:Randonne:edit" }
    methods:  [GET, POST]

randonne_delete:
    path:     /delete/{idrando}
    defaults: { _controller: "ExcursionBundle:Randonne:delete" }
    methods:  DELETE

randonne_old:
    path:     /old
    defaults: { _controller: "ExcursionBundle:Randonne:old" }
    methods:  GET

randonne_active_admin:
    path:     /active
    defaults: { _controller: "ExcursionBundle:Randonne:newadmin" }
    methods:  GET

randonne_old_admin:
    path:     /oldadmin
    defaults: { _controller: "ExcursionBundle:Randonne:oldadmin" }
    methods:  GET

randonne_reserve:
    path:     /reserve/{idrando}
    defaults: { _controller: "ExcursionBundle:Randonne:reserve" }
user_randonne:
    path:   /myexcursion
    defaults: { _controller: "ExcursionBundle:Randonne:myexcursion" }
cancel_reservation:
    path:   /cancel/{idrando}
    defaults: { _controller: "ExcursionBundle:Randonne:cancel" }

