<?php
/**
 * Created by PhpStorm.
 * User: Sirine
 * Date: 26/11/2018
 * Time: 00:56
 */

namespace VoyageBundle\Repository;
/**
 * ReservationvoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationvoyageRepository extends \Doctrine\ORM\EntityRepository
{





}