<?php
/**
 * Created by PhpStorm.
 * User: Sirine
 * Date: 26/11/2018
 * Time: 00:56
 */

namespace VoyageBundle\Repository;
/**
 * VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyfindAll($destination){
        $query=$this->getEntityManager()
            ->createQuery("select m from VoyageBundle:Voyage m where m.destinationvoyage like :destination");
        $query->setParameter(":destination",'%'.$destination.'%');
        return $query->getResult();
    }


}