user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

excursion:
    resource: "@ExcursionBundle/Resources/config/routing.yml"
    prefix:   /excursion

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

voyage:
    resource: "@VoyageBundle/Resources/config/routing.yml"
    prefix:   /voyage

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event


