user_homepage:
    path:     /
    defaults: { _controller: "UserBundle:Default:index" }
user_profile:
    path:     /profil
    defaults: { _controller: "UserBundle:user:show" }

user_edit:
    path:     /profile/ed
    defaults: { _controller: "UserBundle:user:edit" }