<?php

namespace HotelBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{

    public function myfindall($adresse){
        $query=$this->getEntityManager()
            ->createQuery("select m from HotelBundle:Hotel m where m.adressehotel='$adresse'");
        return $query->getResult();
    }
    public function myfindallbyname($adresse){
        $query=$this->getEntityManager()
            ->createQuery("select m from HotelBundle:Hotel m where m.adressehotel like :adresse");
        $query->setParameter(":adresse",'%'.$adresse.'%');
        return $query->getResult();
    }



    public function countHotel($name, $adresse)
    {
        $query  = $this->getEntityManager()->createQuery("SELECT count(h.idhotel) as nmbre FROM HotelBundle:Hotel h WHERE h.namehotel='$name' and h.adressehotel='$adresse'");
        return $query->getResult();
    }


    public function hotelFind($id)
    {
        $query = $this->getEntityManager()->createQuery("SELECT R from HotelBundle:Hotel R WHERE R.idhotel = :id");
        $query->setParameter(':id',$id);
        return $query->getResult();
    }

}
