<?php

namespace HotelBundle\Repository;

/**
 * ReservationHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationHotelRepository extends \Doctrine\ORM\EntityRepository
{





}
