<?php
/**
 * Created by PhpStorm.
 * User: STA
 * Date: 25/11/2018
 * Time: 04:56
 */

namespace ExcursionBundle\Repository;

/**
 * ExcursionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ExcursionRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindByNewDate()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT * FROM randonne WHERE `dateRando` > CURDATE() GROUP BY dateRando");
        return $query->getResult();
    }

    public function findByOldDate()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT * FROM randonne WHERE `dateRando` <= CURDATE() GROUP BY dateRando");
        return $query->getResult();
    }

    public function countNewExcursion()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT count(*) FROM randonne WHERE `dateRando` > CURDATE()");
        return $query->getResult();
    }

    public function countOldExcursion()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT count(*) FROM randonne WHERE `dateRando` <= CURDATE()");
        return $query->getResult();
    }

    public function countAllExcursion()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT count(*) FROM randonne");
        return $query->getResult();
    }
}