<?php

namespace ActivityBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindOneByAdresseactivite($adresseactivite)
    {
        $query=$this->getEntityManager()->createQuery("select a from ActivityBundle:Activity a where a.adresseactivite like :ad");
        $query->setParameter(':ad', '%'.$adresseactivite.'%');
        return $query->getResult();
    }


    public function myfindByTypeDql($typeactivite)
    {
        $qd=$this->getEntityManager()
            ->createQuery("SELECT a FROM ActivityBundle:Activity a WHERE a.typeactivite LIKE :typeactivite")
            ->setParameter(':typeactivite',$typeactivite);
        return $qd->getResult();
    }
    public function myfindall($adresseactivite)
    {
        $query=$this->getEntityManager()->createQuery("select m from ActivityBundle:Activity  m where m.adresseactivite='$adresseactivite'");
        return $query->getResult();
    }
}
