<?php

namespace ActivityBundle\Repository;

/**
 * ActivityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
